name: Add PR to GitHub Project

on:
  pull_request:
    types: [opened]

jobs:
  add_to_project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1
        with:
          project-url: https://github.com/users/davinceleecode/projects/3
          github-token: ${{ secrets.GITHUB_TOKEN }}
